### ISSUE TITLE
Make Signal and Algorithm pickable

### ISSUE THREAD

**Issue by andbiz** [MPBA/pyphysio#18]

**Comment by Alebat** [comment]
Could you post a non working example of pickleing-unpickleing?

**Comment by andbiz** [comment]
The main problem is that currently class attributes (?), e.g. start_time, sampling_freq, are not saved.

**Save**
`
import pickle
import pyphysio as ph

ibi = ...
pickle.dump(ibi, open( "ibi.p", "wb" ) )
`
or:
`
import pyphysio as ph
ibi.save('ibi.p')
`
**Load**
`
import pickle
import pyphysio as ph

ibi = pickle.load( open( "ibi.p", "rb" ) )
`
or
`
import pyphysio as ph
ibi = ph.load_pk('ibi.p')
`

**Comment by Alebat** [comment]
Must use sign.p to retrieve something pickleable and

**Comment by andbiz** [comment]
create a method in Signal, e.g.:

```
def to_pickle(filename, gzip=True):
    #saves a pickle file (with optional gzip compression)
    if gzip:
        f = gzip.open(filename, mode="wb")
    else:
        f = open(filename, mode="wb")
    pickle.dump(signal.pickleable, f)
    f.close()
    print('saved in: '+os.getcwd())
```
And analogous 
from_pickle(filename)

to load a Signal from a pickle file

**Comment by andbiz** [comment]
Sorry, there is already the method save_pickle...
Changed name to to_pickle (develop-andrea)

**Comment by Alebat** [comment]
Should I also rename load_pickle to from_pickle
