### ISSUE TITLE
change repo name to pyphysio

### ISSUE THREAD

**Issue by andbiz** [MPBA/pyphysio#36]

**Comment by Alebat** [comment]
@ernestoarbitrio could you please? :smile: Just do it;

@andbiz when you won't be able to fetch/push do this
> git remote -v
> git remote set-url origin git@github.com:MPBA/pyphysio.git
> git remote -v

and check the output

**Comment by ernestoarbitrio** [comment]
Done! @Alebat

**Comment by Alebat** [comment]
Thanks!
