### ISSUE TITLE
_param_descriptors removal

### ISSUE THREAD

**Issue by andbiz** [MPBA/pyphysio#37]
Provide documentation through \_\_init\_\_ instead of _params_descriptors

**Comment by Alebat** [comment]
Should we completely remove _params_descriptors? How do we do the sanity check for parameters?
**Through assertions in \_\_init\_\_**
Isn't it ugly to put assertions?
**No, parameters should have correct values**

**Comment by Alebat** [comment]
I think it is better to split the task in three phases:

- [ ] Add the \_\_init\_\_ method to every Algorithm
- [ ] Write docstrings from _params_descriptors
- [ ] Add assertions with appropriate messages

**Comment by Alebat** [comment]
Now you can use the script!
E.g. for InBand(freq_min, freq_max, method)
`$ python initize.py _Indicator freq_min freq_max method`
Gives as output:
>     def __init__(self, freq_min, freq_max, **kwargs):
>         _Indicator.__init__(self, freq_min=freq_min, freq_max=freq_max, **kwargs)

**Comment by Alebat** [comment]
@andbiz can you search for "(Andrea)" in the project? There are some pending fixes. If you can check also the other TODOs please.

**Comment by Alebat** [comment]
- [ ] Check that nested algorithm calls of algorithms with parameters are performed within __init__
