### ISSUE TITLE
TODOs Andrea

### ISSUE THREAD

**Issue by Alebat** [MPBA/pyphysio#41]
Added todos in `test_indicators_hrv.py` (search for `TODO Andrea`)

**Comment by Alebat** [comment]
(remember to merge develop before working)

**Comment by Alebat** [comment]
I added some `TODO (Andrea)` and `FIXME (Andrea)`, the latter in this case have the precedence

**Comment by andbiz** [comment]
Removed all TODOs and FIXMEs Andrea.
Closed
