### ISSUE TITLE
ModuleNotFoundError: No module named 'approx'

### ISSUE THREAD

**Issue by mmi-tonicapo** [MPBA/pyphysio#53]
Hello
I am trying to use your library to analyse biosignals data.
I installed it according to instructions but I keep having this error message : 
  File "main.py", line 10, in <module>
    import pyphysio as ph
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyphysio/__init__.py", line 23, in <module>
    from .tests import TestData
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyphysio/tests/__init__.py", line 13, in <module>
    import approx as approx
ModuleNotFoundError: No module named 'approx'

I must say I'm new at using Python. Can you help me with this issue?
Thank you!

**Comment by andbiz** [comment]
Hi!

This is probably due to a wrong version of the pytest library.
Please try installing it from command line, e.g. using pip:
$ pip install pytest

**Comment by mmi-tonicapo** [comment]
Thank you for the help. It worked!

**Comment by andbiz** [comment]
Glad it helped. I am closing the issue.

Please also consider using the develop-andrea branch which is more updated.
We plan to merge it in the master branch asap.
