### ISSUE TITLE
__new__() got an unexpected keyword argument 'signal_type'

### ISSUE THREAD

**Issue by Gioelson95** [MPBA/pyphysio#57]
In the tutorials, when creating a signal I got this error, how to fix it?

**Comment by andbiz** [comment]
Thanks for using pyphysio!

The 'signal_type' argument was introduced recently to replace the 'signal_nature' argument.
It seems you are using an old version of the library.

Please ensure you are using the last version of the library (the development is still ongoing so new versions are released quite often).

Please note that now you can install pyphysio through pip.

I am closing the issue as all tutorial notebooks are executed correctly on my machine (Python 3.7, Jupyter Lab 1.0.2).

If you still encounter the error, please open a new issue and remember to report which notebook you were using and the full trace of the error. Thanks!
